name: android

on:
  push:
    branches: [ started-android-with-jni ]
#  pull_request:
#    branches: [ started ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          # cache: gradle

      #        - name: create avd
      #          run: |
      #            SYSTEM_IMAGES="system-images;android-30;google_apis;x86"
      #            $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/./sdkmanager "$SYSTEM_IMAGES"
      #            $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/./sdkmanager "emulator"
      #            echo "no" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/./avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"
      #            $ANDROID_SDK_ROOT/emulator/./emulator -avd test -delay-adb -verbose -no-window -noaudio -no-boot-anim -memory 4096 -accel on -qemu -disable-kvm

      - name: generate key store
        run: |
          [ ! -d ~/.android ] && mkdir ~/.android
          echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: upload outputs
        uses: actions/upload-artifact@v3
        with:
          name: outputs
          path: app/build/outputs

      - name: upload apk debug
        uses: actions/upload-artifact@v3
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: upload apk release
        uses: actions/upload-artifact@v3
        with:
          name: apk-release
          path: app/build/outputs/apk/release/app-release.apk