name: LINUX_OS_TEST

on:
  push:
    branches:
      - "*"
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level:
          - 23
          - 36
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      API_LEVEL: ${{ matrix.api-level }}
      ANDROID_AVD_HOME: $HOME/.config/.android
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup directory AVD
        run: |
          ANDROID_AVD_DIR=~/.android/avd
          mkdir -pv $ANDROID_AVD_DIR
          sudo mount -v none -t tmpfs -o rw,noatime,nodiratime,size=100%,nr_inodes=0,mode=755,uid=$USER,gid=$USER,inode64 $ANDROID_AVD_DIR

      - name: Setup directory Gradle
        run: |
          GRADLE_DIR=~/.gradle
          mkdir -pv $GRADLE_DIR
          sudo mount -v none -t tmpfs -o rw,noatime,nodiratime,size=100%,nr_inodes=0,mode=755,uid=$USER,gid=$USER,inode64 $GRADLE_DIR

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "jetbrains"

      - name: Gradle cache
        uses: actions/cache@v5
        id: gradle-cache
        with:
          path: |
            ~/.gradle
            ~/.m2
          key: gradle-${{ github.job }}-${{ hashFiles('versions.gradle') }}

      - name: AVD cache
        uses: actions/cache@v5
        id: avd-cache
        with:
          path: |
            /usr/local/lib/android/sdk/system-images
          key: avd-${{ github.job }}-${{ matrix.api-level }}

      - name: Generate keystore
        run: |
          [ ! -d ~/.android ] && mkdir ~/.android
          echo y | keytool -genkey -dname "cn=debug, ou=debug, o=debug, c=debug" -alias androiddebugkey -keypass android --storepass android -keyalg RSA -keystore ~/.android/debug.keystore -validity 10000

      - name: Replace org.gradle.jvmargs
        run: |
          ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
          sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
          cat gradle.properties | grep org.gradle.jvmargs

      - name: Start AVD
        run: |
          # Setup KVM Group Permission
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

          # AVD Dependencies
          sudo apt-get update
          sudo apt-get install --no-install-suggests --no-install-recommends mesa-vulkan-drivers libpulse0 -y

          export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator"

          yes | sdkmanager --licenses
          sdkmanager --update
          sdk_manager_channel="--channel=0"
          echo y | sdkmanager --install emulator $sdk_manager_channel
          echo y | sdkmanager --install "system-images;android-$API_LEVEL;default;x86_64" $sdk_manager_channel
          mkdir -pv $ANDROID_AVD_HOME
          sudo mount -v none -t tmpfs -o rw,noatime,nodiratime,size=100%,nr_inodes=0,mode=755,uid=$USER,gid=$USER,inode64 $ANDROID_AVD_HOME
          avdmanager create avd --force -n "test" -k "system-images;android-$API_LEVEL;default;x86_64" -d "17"
          adb kill-server && adb start-server
          if [ $API_LEVEL -lt 26 ]; then
            emulator -avd test -metrics-collection -log-nofilter -no-boot-anim -nocache -no-snapstorage -no-snapshot -no-snapshot-load -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -camera-back none -accel on -memory $(expr 1024 \* 2) -cores 2 &
          else
            emulator -avd test -metrics-collection -log-nofilter -no-boot-anim -nocache -no-snapstorage -no-snapshot -no-snapshot-load -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -camera-back none -accel on -qemu -cpu host,kvm=on -smp $(nproc) -m $(expr 1024 \* 6) &
          fi

      - name: Run Build
        run: |
          export PATH=$PATH:$ANDROID_HOME/platform-tools
          adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done;'
          adb shell settings put global window_animation_scale 0.0
          adb shell settings put global transition_animation_scale 0.0
          adb shell settings put global animator_duration_scale 0.0
          adb shell input keyevent 82
          ./gradlew clean build